<?php 
  
$page = 'Home | Pasig E-Scholar';
include('Head.php');
require_once 'Includes/dbconfig.php';


?>


<style>
body {
    background-color: #003067;
}

.hero-image {


    background: linear-gradient(0deg, rgba(1, 64, 107, 0.67), rgba(1, 64, 107, 0.67)), url('Assets/Background.gif');
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: cover;
    height: 850px !important;
    margin-top: 5% !important;
    color: #fff;
    margin-bottom: 0px;

}

.scholar_img {
    border: 1px solid #f5d465 !important;
    width: 100%;
    border-radius: 50px 100px 10px;
    box-shadow: 0 10px 5px -2px rgba(0, 0, 0, 0.2) !important;
}




.col-md-8 h1 {
    font-size: 56px !important;
    -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}

.col-md-8 p {
    font-size: 16px !important;
    -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;

}

.school_year {
    color: #f5d465 !important;
    font-family: 'Montserrat', sans-serif !important;

    text-transform: uppercase;

    font-weight: bold;
    text-shadow: 3px 3px #333;


}



.this {

    padding-top: 8% !important;
    padding-bottom: 280px !important;
}

.this .btn {
    border: 2px solid #fff !important;
    color: #fff !important;
    border-bottom: 2px solid rgba(22, 22, 26, 0.18);
    font-size: 20px !important;
    box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.2) !important;
    -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}





.acitve {
    background: #dd3e2b !important;

}

.col-md-4 img {
    width: 100% !important;


    -webkit-animation: swirl-in-fwd 0.6s ease-out both;
    animation: swirl-in-fwd 0.6s ease-out both;

}

/* ----------------------------------------------
 * Generated by Animista on 2023-2-20 10:38:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
    0% {
        letter-spacing: -0.5em;
        opacity: 0;
    }

    40% {
        opacity: 0.6;
    }

    100% {
        opacity: 1;
    }
}

@keyframes tracking-in-expand {
    0% {
        letter-spacing: -0.5em;
        opacity: 0;
    }

    40% {
        opacity: 0.6;
    }

    100% {
        opacity: 1;
    }
}

/* ----------------------------------------------
 * Generated by Animista on 2023-2-20 10:37:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swirl-in-fwd
 * ----------------------------------------
 */
@-webkit-keyframes swirl-in-fwd {
    0% {
        -webkit-transform: rotate(-540deg) scale(0);
        transform: rotate(-540deg) scale(0);
        opacity: 0;
    }

    100% {
        -webkit-transform: rotate(0) scale(1);
        transform: rotate(0) scale(1);
        opacity: 1;
    }
}

@keyframes swirl-in-fwd {
    0% {
        -webkit-transform: rotate(-540deg) scale(0);
        transform: rotate(-540deg) scale(0);
        opacity: 0;
    }

    100% {
        -webkit-transform: rotate(0) scale(1);
        transform: rotate(0) scale(1);
        opacity: 1;
    }
}

























.mobile_img {
    display: none !important;
    -webkit-animation: swirl-in-fwd 0.6s ease-out both;
    animation: swirl-in-fwd 0.6s ease-out both;
}

.our_services {
    padding: 10px !important;
    height: 100% !important;
}

.our_services .title {

    color: #fff !important;
    padding-top: 50px !important;
    padding-bottom: 20px !important;
    text-align: center !important;
}

.our_services .title h1 {
    font-size: 56px !important;
}

.our_services .title h1 span {
    color: #fcd116 !important;
}

.our_services .title p {
    font-size: 20px !important;
}

.flex-box {
    display: flex !important;
    justify-content: space-between !important;
}

.box {
    color: #003067 !important;
    border-radius: 20px !important;
    width: 100%;
    margin: 10px !important;
    padding: 15px !important;
    text-align: center;
    background: #fff !important;
    border-bottom: 2px solid rgba(22, 22, 26, 0.18);
    box-shadow: 0 10px 5px -2px rgba(0, 0, 0, 0.2) !important;


}

.box:hover {

    background: #fcd116 !important;
    transition: 0.5s !important;
    cursor: pointer !important;
}

.box h5 {
    font-size: 22px !important;

}

.box i {

    font-size: 100px !important;
    padding: 10px !important;
    margin-bottom: 20px !important;
}

.page3 {

    padding: 10px !important;
    margin-top: 5% !important;
    color: #fff !important;
    margin-bottom: 5% !important;
}




.page3 h2 span {
    color: #fcd116 !important;
}

.page3 i {

    color: #fcd116 !important;
}

.admins-container,
.feedbacks {

    background-image: url(assets/BackgroundTip.jpg);
    background-size: cover;
    background-attachment: fixed;
    background-position: center;
    margin-bottom: 0px !important;

    padding-bottom: 120px !important;
    padding-top: 50px !important;

}

.admin_card {
    width: 100% !important;
    background: #fff !important;
    box-shadow: 0 10px 5px -2px rgba(0, 0, 0, 0.2) !important;
    padding: 0% !important;
    border-radius: 10px !important;
    margin-bottom: 65px !important;
    height: 470px !important;
    cursor: pointer !important;
}

.admin_card h5,
.admin_card span {

    color: #003067 !important;
    font-weight: 1000 !important;
}

.hedaer {
    color: #003067 !important;
}

.admin_card img {
    width: 100% !important;
    height: 360px !important;




}

.fa-users-gear {
    font-size: 110px !important;
    margin-bottom: 15px !important;
}

.greetings {
    color: #f5d465 !important;
    font-family: 'Montserrat', sans-serif !important;
    font-weight: bold;
    text-shadow: 3px 3px #333;

}

.faq-container-fluid {
    padding-top: 3% !important;
    padding-bottom: 8% !important;
}

.faq-container {
    padding: 10px !important;
    margin: 10px auto;
    color: #fff;

}

.faq-question {

    box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.2) !important;
    margin: 20px 0;
    padding: 0px !important;
    border: 2px solid #000 !important;
    background: #fff !important;
}

.question h3 {
    color: white !important;
    font-size: 20px;
}

.question {
    padding: 15px 10px !important;
    margin: 0;

    background: #dd3e2b !important;
    cursor: pointer;
    position: relative;
}

.answer {

    overflow: hidden;
    background: #fff !important;
    color: #000;
    padding: 15px !important;
    display: none;
    border-top: 2px solid black !important;


}

.question i {

    width: 10% !important;

    font-size: 30px;

}

.fa-circle-question {
    font-size: 100px !important;
    margin-bottom: 26px !important;
}



































@media screen and (max-width: 1000px) {


    .hero-image {

        margin-top: 0% !important;
        text-align: center;
        height: 100% !important;
        display: flex;
        align-items: center !important;


    }



    .admin_card {
        height: 100% !important;

    }

    .Unleash {
        font-size: 20px !important;
    }


    .admin_card img {
        width: 100% !important;
        height: 300px !important;




    }

    .admin_card h5 {
        font-size: 14px !important;
    }



    .desktop_logo {
        display: none !important;
    }

    .col-md-8 h1 {
        font-size: 30px !important;
    }

    .mobile_img {
        display: block !important;
        width: 200px !important;
        margin: 0 auto !important;
    }

    .flex-box {
        align-items: center !important;
        flex-direction: column !important;
    }

    .page3 img {
        width: 100%;
        border-radius: 0px !important;
        margin-bottom: 20px !important;
    }

    .this {

        padding-top: 36% !important;
        padding-bottom: 150px !important;

    }

    .our_services .title h1 {
        font-size: 40px !important;
    }

    .greetings {
        font-size: 20px !important;
        margin-top: 20px !important;
    }


    .question h3 {
        color: white !important;
        font-size: 13px !important;
    }

    .question i {
        font-size: 15px !important;
        right: 5px !important;
    }


}

</style>
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>


<link rel="stylesheet" type="text/css" href="css/timeline.css?<?php echo time(); ?>" />


<div class="hero-image container-fluid main">

    <div class="container py-5 this">
        <div class="row align-items-center align-content-center">
            <div class="col-md-8 mt-5 mb-5">
                <img class="mobile_img" src="Assets/PST_LOGO.png" alt="">
                <?php if(isset($_SESSION['authenticanted'])): ?>
                <h2 class="greetings text-capitalize">Hi, <?php echo $_SESSION['auth_user']['first_name'] ?> 👋 Welcome
                    to </h2>
                <?php endif; ?>
                <h1> Pasig City Scholars
                </h1>
                <h1 class="school_year"><i class="fa-solid fa-graduation-cap"></i> A.Y
                    <?php echo bcsub(date("Y"),1)."-".date("Y"); ?></h1>

                <h5>Pasig City Scholars is a program initiated by the local government of Pasig City, Philippines, to
                    provide financial assistance and educational opportunities to deserving students in the city.
                </h5>
                <a href="application_form.php" type="button" class="btn btn-primary acitve"><i
                        class="fa-solid fa-right-to-bracket mr-2"></i>APPLY</a>
                <a type="button" href="#our_services" class="btn btn-outline-primary">LEARN MORE</a>






            </div>
            <div class="col-md-4"><img class="desktop_logo" src="Assets/PST_LOGO.png" alt=""></div>
        </div>

    </div>

</div>


<div class="our_services mb-5 ">
    <div class="container">
        <div class="title" id="our_services" data-aos="fade-up">
            <h1><span>Our</span> Services</h1>
            <h5>Web-based E-scholar Tracking and Management System provides a comprehensive overview of the various
                services available to scholars.</h5>
        </div>
        <div class="flex-box">
            <div class=" box" data-aos="fade-down">
                <i class="fa-solid fa-desktop"></i>
                <h5>Responsive</h5>
                <p>Users can access and interact with the website easily, no matter what device they are using.</p>
            </div>
            <div class="box" data-aos="fade-up">
                <i class="fa-solid fa-chart-pie"></i>
                <h5>Application Tracking</h5>
                <p>To provide users with visual feedback on the status of their application.</p>
            </div>
            <div class="box" data-aos="fade-up">
                <i class="fa-solid fa-note-sticky"></i>
                <h5>Fast Approval</h5>
                <p>Uses algorithms to pre-screen and score applications, reducing manual review and speeding up
                    decisions.</p>
            </div>
            <div class="box" data-aos="fade-down">
                <i class="fa-solid fa-user-graduate"></i>
                <h5>Scholar List</h5>
                <p>Help users find and access information about scholars quickly and efficiently.</p>
            </div>
        </div>

    </div>
</div>


<div class="page3 container-fluid mt-5 ">
    <div class="container ">
        <div class="row align-items-center align-content-center">
            <div class="col-md-5 " data-aos="slide-up">
                <img class="scholar_img"
                    src="https://images.pexels.com/photos/207569/pexels-photo-207569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                    alt="">
            </div>
            <div class="col-md-7" data-aos="flip-right">

                <h2 class="Unleash"><span>Unleash Your Potential:</span> Apply for Pasig City Scholarship Today!</h2>
                <h5>Invest in your future and unlock your potential with Pasig City Scholarship! This program offers
                    financial assistance and support to deserving students who are dedicated to pursuing their
                    dreams.
                </h5>

                <div class="row">
                    <div class="col-md-6">
                        <h6><i class="fa-regular fa-circle-check mr-2"></i>Financial support</h6>
                    </div>
                    <div class="col-md-6">
                        <h6><i class="fa-regular fa-circle-check mr-2"></i>Reduced debt burden</h6>
                    </div>
                    <div class="col-md-6">
                        <h6><i class="fa-regular fa-circle-check mr-2"></i>Increased academic performance</h6>
                    </div>
                    <div class="col-md-6">
                        <h6><i class="fa-regular fa-circle-check mr-2"></i>Networking opportunities</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="container-fluid feedbacks">
    <div class="container text-center">
        <h2><i class="fa-solid fa-location-dot mr-2"></i>Pasig City Scholarship Office Address</h2>
        <h5>Pasig City Scholarship Office is located at City Hall, Caruncho Avenue, Barangay San Nicolas, Pasig City,
            Philippines. Our office is on the ground floor of the City Hall building. For inquiries, call (02)
            8-642-5287 or email scholarships@pasigcity.gov.ph.</h5>
        <hr>
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3861.703418110199!2d121.07822937508513!3d14.558945278095154!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c878b27cf29f%3A0x25b77d115c9069f9!2sCaruncho%20Ave%2C%20Pasig%2C%20Metro%20Manila!5e0!3m2!1sen!2sph!4v1683019927534!5m2!1sen!2sph"
            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

</div>






<!-- <div class="container-fluid">
    <div class="container faq-container-fluid" data-aos="flip-right">

        <div class="faq-container">
            <div class="faq-header text-center">
                <i class="fa-regular fa-circle-question"></i>
                <h2>Frequently Asked Questions</h2>

            </div>
            <?php 

        $query = "SELECT * FROM  faq_list";
        $query_run = mysqli_query($conn,$query);


        if (mysqli_num_rows($query_run) > 0) {
        while ($row=mysqli_fetch_assoc($query_run)) {

            ?>
            <div class="faq-question">
                <div class="question row">
                    <div class="col-md-11">
                        <h3 class=""><?php echo $row['question'] ?></h3>
                    </div>
                    <div class="col-md-1">
                        <i class="fa-solid fa-square-caret-down"></i>
                    </div>
                </div>
                <div class="answer">
                    <h5><?php echo $row['answer'] ?></h5>
                </div>


            </div>
            <?php
        }
        }

        ?>

        </div>






    </div>
</div> -->



<!-- <div class="container-fluid">
    <img src="Assets/Frame 6.png" style="width:100%" alt="">
    <br>
    <br>
</div> -->



<div class="container-fluid">
    <div class="container mb-5 ">
        <div class="timeline-header">
            <h1><span>How</span> to Apply</h1>
            <p>By following the instructions provided, students can increase their chances of receiving a scholarship
                and
                fulfilling their educational goals.</p>
        </div>
        <div class="text-center text-light arrows">
            <h4 class="">Start</h4>
            <i class="fa-solid fa-arrow-down mb-2"></i>
        </div>

        <div class="timeline">

            <div class="timeline-row" data-aos="fade-left" data-aos-duration="1000">
                <div class="timeline-time">
                    <h3>1st</h3>
                    <p>Fill-Up Application Form</p>

                </div>
                <div class="timeline-content text-light">

                    <i class="fa-solid fa-user"></i>

                    <p>The process of applying for a scholarship. New applicants apply for the scholarship for the first
                        time, while renewal applicants seek to renew it. </p>
                </div>
            </div>

            <div class="timeline-row" data-aos="fade-right" data-aos-duration="1000">
                <div class="timeline-time">
                    <h3>2nd</h3>
                    <p>Fill-Up Application Form</p>

                </div>
                <div class="timeline-content text-light">
                    <i class="fa-regular fa-address-book"></i>

                    <p>Filling out the scholarship application form is a crucial step in applying for scholarship. It
                        requires providing personal, academic, and financial information, along with any required
                        supporting documents.</p>
                </div>
            </div>

            <div class="timeline-row" data-aos="fade-left" data-aos-duration="1000">
                <div class="timeline-time">
                    <h3>3rd</h3>
                    <p>Uploading of Requirements</p>

                </div>
                <div class="timeline-content text-light">
                    <i class="fa-solid fa-paperclip"></i>
                    <p>This procedure involves providing scanned copies of mandatory documents, including an enrollment
                        form, transcripts, essays, Certification of Residency, and financial statements.</p>
                </div>
            </div>

            <div class="timeline-row" data-aos="fade-right" data-aos-duration="1000">
                <div class="timeline-time">
                    <h3>4th</h3>
                    <p>If Scholar Applicant is Approved</p>

                </div>
                <div class="timeline-content text-light">
                    <i class="fa-regular fa-circle-check"></i>
                    <p>Scholar applicants who are approved for a scholarship will receive a notification via email. Once
                        the scholarship evaluator reviews the applications, they will send an email to successful
                        applicants informing them of their approval.

                    </p>
                </div>
            </div>

            <div class="timeline-row" data-aos="fade-left" data-aos-duration="1000">
                <div class="timeline-time ">
                    <h3>5th</h3>
                    <p>Scholarship Application Disapproved</p>
                </div>
                <div class="timeline-content text-light">
                    <i class="fa-solid fa-arrow-rotate-left"></i>
                    <p>If a scholarship application is disapproved due to missing or incomplete requirements, the
                        applicant may re-submit the necessary documents for reconsideration. Additionally, the applicant
                        will receive an email detailing the reason for the disapproval. Depending on the reason for
                        disapproval, the applicant may be able to re-apply for the scholarship.

                    </p>
                </div>
            </div>
        </div>
        <div class="text-center text-light arrows">
            <i class="fa-solid fa-arrow-down"></i>
            <h4 class="">End</h4>
        </div>
    </div>
</div>
































<script>
const questions = document.querySelectorAll('.question');

questions.forEach(question => {
    question.addEventListener('click', () => {
        const answer = question.nextElementSibling;
        if (answer.style.display === 'block') {
            answer.style.display = 'none';


            const icon = question.querySelector('i');
            icon.classList.toggle('fa-square-caret-down');
            icon.classList.toggle('fa-square-caret-up');



        } else {
            answer.style.display = 'block';
            const icon = question.querySelector('i');
            icon.classList.toggle('fa-square-caret-down');
            icon.classList.toggle('fa-square-caret-up');
        }
    });
});
</script>













<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
AOS.init();
</script>




<?php 


include('Footer.php');



?>
