<?php 



$page='Resubmit';
include('includes/dbconfig.php');
include('includes/header.php');
include('includes/navbar.php');


?>
<style>
.square {
    display: inline-block;
    width: 1em;
    height: 1em;
}

table {
    border: 1px solid grey !important;
}

table tr th {
    border-bottom: 1px solid grey !important;
    border-top: 1px solid grey !important;
    padding: 10px !important;
    width: 60% !important;
}

.card-body h3 {
    background-color: #003067 !important;
    padding: 7px 10px !important;
    color: white !important;
    box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.2) !important;
}

.card-body h5 span {
    color: #003067 !important;
    font-weight: 700 !important;


}

table tr th {

    padding: 15px !important;
}

.applicant_img {
    width: 200px !important;
    margin: 10px auto !important;
}

.modal-body img {
    width: 100%;
    height: 400px !important;
}



.essay,
.Proof_of_Enrollment,
.Report_Card,
.Barangay_Residency,
.Proof_of_Income {

    position: absolute !important;
    z-index: 1 !important;
    width: 70% !important;
    background-color: rgb(50, 54, 57) !important;
    padding: 15px 20px !important;
    left: 230px !important;
    top: 10px !important;
    color: white !important;
    -webkit-animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;

}



.hide {
    display: none;
}


/* ----------------------------------------------
 * Generated by Animista on 2023-2-15 20:36:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-top
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-top {
    0% {
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }

    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }
}

@keyframes scale-up-top {
    0% {
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }

    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }
}

</style>
<?php 

if(isset($_POST['application_view'])){


    $application_id = $_POST['application_id'];
    $application_email = $_POST['application_email'];


    $query = "SELECT * FROM applicants_table WHERE isApproved='false' AND resubmit='true' AND id='$application_id' AND email='$application_email'";
 
 
    $query_run = mysqli_query($conn,$query);

    foreach ($query_run as $row) {
        ?>


<div class="container-fluid" style="position:relative ">
    <div class="border hide" id="essay">

        <div class="essay">
            <h2>View Essay</h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Essay'] ?>" width="100%" height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary" id="done_view_esssay">DONE</button>
        </div>
    </div>
    <div class="border hide" id="Proof_of_Enrollment">

        <div class="Proof_of_Enrollment">
            <h2>View Proof of Enrollment </h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Proof_of_Enrollment'] ?>" width="100%"
                height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary"
                id="done_view_Proof_of_Enrollment">DONE</button>
        </div>
    </div>
    <div class="border hide" id="Report_Card">

        <div class="Report_Card">
            <h2>View Report Card</h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Report_Card'] ?>" width="100%"
                height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary" id="done_Report_Card">DONE</button>
        </div>
    </div>
    <div class="border hide" id="Proof_of_Income">

        <div class="Proof_of_Income">
            <h2>View Proof of Income</h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Proof_of_Income'] ?>" width="100%"
                height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary" id="done_Proof_of_Income">DONE</button>
        </div>
    </div>

    <div class="card shadow mb-4">

        <div class="card-header">
            <div class="flex-box" style="display:flex; justify-content:space-between">
                <h2 class="mb-0">Pending Resubmit Checklist</h2>
                <div>
                    <a type="button" href="Resubmit.php" class="btn btn-danger">BACK</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?php include('sweetAlert.php');?>
            <div class="card-body">

                <div class="row">
                    <div class="col-md-4 border p-4">
                        <div class="mb-5 text-center">
                            <img class="mb-5 border rounded-circle" width="250px" height="250px"
                                src='<?php echo "upload_docu/".$row['fileName']."/".$row['picture'] ?>'>
                            <h4><?php echo $row['full_name']?></h4>
                            <hr>
                            <div class="contact-information text-left">
                                <h3 class="mb-4">Contact Information</h3>
                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-mobile mr-2"></i>Phone:</span>
                                    <?php echo $row['Contact_number']?>
                                </h5>
                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-location-dot mr-2"></i>Address:</span>
                                    <?php echo $row['house_number']." ".$row['Street']." ".$row['barangay']?>
                                </h5>


                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-envelope mr-2"></i>Email:</span>
                                    <?php echo $row['email']?>
                                </h5>

                                <h3 class="mb-4 mt-4">Basic Information</h3>


                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-cake-candles mr-2"></i>Date of Birth:</span>
                                    <?php echo date("F j, Y", strtotime($row['Date_of_birth'])); ?>
                                </h5>


                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-person-half-dress mr-2"></i>Gender:</span>
                                    <?php echo $row['gender']?>
                                </h5>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-8 border p-4">


                        <h3>Documents</h3>


                        <br>





                        <table width="100%">
                            <thead>
                                <?php if($row['get_allowance'] == 'true'): ?>
                                <tr>
                                    <th>
                                        <h4 class="text-danger text-capitalize">Note: This Scholar is already recieve
                                            allowance on
                                            <span><?php echo date("F j, Y, g:i a", strtotime($row['allowance_get_date']));?></span>
                                        </h4>
                                    </th>
                                </tr>
                                <?php endif; ?>


                                <tr>
                                    <th>Reference Number</th>
                                    <th><?php echo $row['applicantion_reference_number']; ?></th>
                                </tr>
                                <tr>
                                    <th>Scholar Type</th>
                                    <th><?php echo $row['scholar_type'];?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr
                                    class="bg-<?php echo $row['school_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>School</th>
                                    <th class="text-capitalize"><?php echo $row['school'];?></th>
                                </tr>

                                <tr
                                    class="bg-<?php echo $row['valid_id_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>Valid ID</th>
                                    <th><button type="button" data-toggle="modal" data-target="#Valid_ID"
                                            class="btn btn-primary">View Here</button>

                                        <?php if($row['valid_id_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>
                                    </th>
                                    <!-- Modal -->
                                    <div class="modal fade" id="Valid_ID" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Valid ID
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <img src="<?php echo "upload_docu/".$row['fileName']."/".$row['valid_id'] ?>"
                                                        alt="sadsads">
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="width:100%" type="button" class="btn btn-primary"
                                                        data-dismiss="modal">DONE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                                <tr
                                    class="bg-<?php echo $row['School_ID_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>School ID</th>
                                    <th><button data-toggle="modal" data-target="#School_ID" type="button"
                                            class="btn btn-primary">View Here</button>
                                        <?php if($row['School_ID_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>
                                    </th>


                                    <!-- Modal -->
                                    <div class="modal fade" id="School_ID" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">School ID
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <img src="<?php echo "upload_docu/".$row['fileName']."/".$row['School_ID'] ?>"
                                                        alt="sadsads">
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="width:100%" type="button" class="btn btn-primary"
                                                        data-dismiss="modal">DONE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                                <tr
                                    class="bg-<?php echo $row['Barangay_Residency_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>Barangay Residency</th>
                                    <th><button type="button" data-toggle="modal" data-target="#View_Barangay_Residency"
                                            class="btn btn-primary">View
                                            Here</button>
                                        <?php if($row['Barangay_Residency_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>

                                    </th>
                                    <!-- Modal -->
                                    <div class="modal fade" id="View_Barangay_Residency" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Barangay
                                                        Residency
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <img src="<?php echo "upload_docu/".$row['fileName']."/".$row['Barangay_Residency'] ?>"
                                                        alt="sadsads">
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="width:100%" type="button" class="btn btn-primary"
                                                        data-dismiss="modal">DONE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                                <?php if($row['scholar_type'] == 'New Applicant'): ?>
                                <tr
                                    class="bg-<?php echo $row['Essay_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>Essay</th>
                                    <th><button class="btn btn-primary" type="button" id="View_essay">View
                                            Here</button>

                                        <?php if($row['Essay_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>

                                    </th>
                                </tr>
                                <?php endif; ?>

                                <tr
                                    class="bg-<?php echo $row['Proof_of_Enrollment_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>Proof of Enrollment</th>
                                    <th><button type="button" id="Proof_of_Enrollment_view" class="btn btn-primary">View
                                            Here</button>

                                        <?php if($row['Proof_of_Enrollment_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>

                                    </th>
                                </tr>
                                <tr
                                    class="bg-<?php echo $row['Report_Card_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>Report Card</th>
                                    <th><button type="button" id="View_Report_Card" class="btn btn-primary">View
                                            Here</button>

                                        <?php if($row['Report_Card_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>

                                    </th>
                                </tr>
                                <tr
                                    class="bg-<?php echo $row['Proof_of_Income_resubmit'] == 'false' ? 'success' : 'danger'; ?> text-white">
                                    <th>Proof of Income</th>
                                    <th><button type="button" id="View_roof_of_Income" class="btn btn-primary">View
                                            Here</button>

                                        <?php if($row['Proof_of_Income_resubmit'] == 'true'){echo '(Resubmit)';}else{echo '(Good)';} ?>

                                    </th>
                                </tr>


                            </tbody>
                        </table>

                        <br>

                        <label>
                            <span class="bg-danger square mr-1"></span>Resubmit <br>
                            <span class="bg-success square mr-1"></span>Good
                        </label>






                        <hr>


                    </div>
                </div>
            </div>





            <?php
                }}
            ?>
        </div>
    </div>
</div>
</div>




<script>
let View_essay = document.getElementById('View_essay');
let done_view_esssay = document.getElementById('done_view_esssay');

View_essay.onclick = () => {
    let essay = document.getElementById('essay');
    essay.classList.remove("hide");
}
done_view_esssay.onclick = () => {
    let essay = document.getElementById('essay');
    essay.classList.add("hide");
}
</script>






<script>
let Proof_of_Enrollment_view = document.getElementById('Proof_of_Enrollment_view');
let View_Report_Card = document.getElementById('View_Report_Card');
let View_roof_of_Income = document.getElementById('View_roof_of_Income');
let done_view_Proof_of_Enrollment = document.getElementById('done_view_Proof_of_Enrollment');
let done_Report_Card = document.getElementById('done_Report_Card');
let done_Proof_of_Income = document.getElementById('done_Proof_of_Income');
Proof_of_Enrollment_view.onclick = () => {
    let Proof_of_Enrollment = document.getElementById('Proof_of_Enrollment');

    Proof_of_Enrollment.classList.remove("hide");
}

done_view_Proof_of_Enrollment.onclick = () => {
    let Proof_of_Enrollment = document.getElementById('Proof_of_Enrollment');
    Proof_of_Enrollment.classList.add("hide");
}

View_Report_Card.onclick = () => {
    let Report_Card = document.getElementById('Report_Card');
    Report_Card.classList.remove("hide");
}
done_Report_Card.onclick = () => {
    let Report_Card = document.getElementById('Report_Card');
    Report_Card.classList.add("hide");
}

View_roof_of_Income.onclick = () => {
    let Proof_of_Income = document.getElementById('Proof_of_Income');
    Proof_of_Income.classList.remove("hide");
}


done_Proof_of_Income.onclick = () => {
    let Proof_of_Income = document.getElementById('Proof_of_Income');
    Proof_of_Income.classList.add("hide");
}
</script>


<?php include('includes/footer.php') ?>
