<?php 


$page='Applicants_Scholar_Table_Checklist';
include('includes/dbconfig.php');
include('includes/header.php');
include('includes/navbar.php');

?>
<style>
table {
    border: 1px solid grey !important;
}

table tr th {
    border-bottom: 1px solid grey !important;
    border-top: 1px solid grey !important;
    padding: 10px !important;
    width: 60% !important;
}

.card-body h3 {
    background-color: #003067 !important;
    padding: 7px 10px !important;
    color: white !important;
    box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.2) !important;
}

.card-body h5 span {
    color: #003067 !important;
    font-weight: 700 !important;


}

table tr th {

    padding: 15px !important;
}

.applicant_img {
    width: 200px !important;
    margin: 10px auto !important;
    height: 190px !important;
}

.modal-body img {
    width: 100%;
}



.essay,
.Proof_of_Enrollment,
.Report_Card,
.Barangay_Residency,
.Proof_of_Income {

    position: absolute !important;
    z-index: 1 !important;
    width: 70% !important;
    background-color: rgb(50, 54, 57) !important;
    padding: 15px 20px !important;
    left: 230px !important;
    top: 10px !important;
    color: white !important;
    -webkit-animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;

}



.hide {
    display: none;
}


/* ----------------------------------------------
 * Generated by Animista on 2023-2-15 20:36:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-top
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-top {
    0% {
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }

    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }
}

@keyframes scale-up-top {
    0% {
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }

    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }
}

</style>
<?php 

if(isset($_POST['application_view'])){


    $application_id = $_POST['application_id'];
    $application_email = $_POST['application_email'];


    $update_to_step3 = "UPDATE users_table SET 
    application_status='step_3'
    WHERE Email = '$application_email'";

    if(mysqli_query($conn,$update_to_step3)){

        date_default_timezone_set('Asia/Manila');
        $get_datetime = date('Y-m-d H:i:s');

        $view_application_query = "UPDATE applicants_table SET date_viewed='$get_datetime' WHERE id='$application_id'";
        mysqli_query($conn,$view_application_query);
    }

 
    $query = "SELECT * FROM applicants_table WHERE id='$application_id' AND isApproved='false'";
    $query_run = mysqli_query($conn,$query);

    foreach ($query_run as $row) {
        ?>





<div class="container-fluid" style="position:relative ">


    <div class="border hide" id="essay">

        <div class="essay">
            <h2>View Essay</h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Essay'] ?>" width="100%" height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary" id="done_view_esssay">DONE</button>
        </div>
    </div>





    <div class="border hide" id="Proof_of_Enrollment">

        <div class="Proof_of_Enrollment">
            <h2>View Proof of Enrollment </h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Proof_of_Enrollment'] ?>" width="100%"
                height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary"
                id="done_view_Proof_of_Enrollment">DONE</button>
        </div>
    </div>



    <div class="border hide" id="Report_Card">

        <div class="Report_Card">
            <h2>View Report Card</h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Report_Card'] ?>" width="100%"
                height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary" id="done_Report_Card">DONE</button>
        </div>
    </div>








    <div class="border hide" id="Proof_of_Income">

        <div class="Proof_of_Income">
            <h2>View Proof of Income</h2>

            <iframe src="<?php echo "upload_docu/".$row['fileName']."/".$row['Proof_of_Income'] ?>" width="100%"
                height="700px">
            </iframe>
            <hr>
            <button style="width:100%" type="button" class="btn btn-primary" id="done_Proof_of_Income">DONE</button>
        </div>
    </div>

    <div class="card shadow mb-4">

        <div class="card-header">
            <div class="flex-box" style="display:flex; justify-content:space-between">
                <h2 class="mb-0">Applicants Scholars View Checklist</h2>
                <div>
                    <a type="button" onclick="location.href = document.referrer; return false;"
                        class="btn btn-danger">BACK</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?php include('sweetAlert.php');?>
            <div class="card-body">

                <div class="row">
                    <div class="col-md-4 border p-4">
                        <div class="mb-5 text-center">
                            <img class="mb-5 border rounded-circle" width="250px" height="250px"
                                src='<?php echo "upload_docu/".$row['fileName']."/".$row['picture'] ?>'>
                            <h4><?php echo $row['full_name']?></h4>
                            <hr>
                            <div class="contact-information text-left">
                                <h3 class="mb-4">Contact Information</h3>
                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-mobile mr-2"></i>Phone:</span>
                                    <?php echo $row['Contact_number']?>
                                </h5>
                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-location-dot mr-2"></i>Address:</span>
                                    <?php echo $row['house_number']." ".$row['Street']." ".$row['barangay']?>
                                </h5>


                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-envelope mr-2"></i>Email:</span>
                                    <?php echo $row['email']?>
                                </h5>

                                <h3 class="mb-4 mt-4">Basic Information</h3>


                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-cake-candles mr-2"></i>Date of Birth:</span>



                                    <?php echo date("F j, Y", strtotime($row['Date_of_birth']));?>
                                </h5>


                                <h5><span class="text-danger text-bold"><i
                                            class="fa-solid fa-person-half-dress mr-2"></i>Gender:</span>
                                    <?php echo $row['gender']?>
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 border p-4">
                        <h3>Documents</h3>
                        <br>
                        <table width="100%">

                            <thead>
                                <tr>
                                    <th>This will be assisted by</th>
                                    <th><?php echo $row['admin_full_name'];?></th>
                                </tr>
                                <tr>
                                    <th>Submitted Date</th>
                                    <th><?php echo date("F j, Y, g:i a", strtotime($row['Date_submitted']));?></th>
                                </tr>
                                <tr>
                                    <th>Applicants Reference Number</th>
                                    <th><?php echo $row['applicantion_reference_number'];?></th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <th>Scholar Type</th>
                                    <th><?php echo $row['scholar_type'];?></th>
                                </tr>

                                <tr>
                                    <th>School</th>
                                    <th><?php echo $row['school'] ?></th>
                                </tr>

                                <tr>
                                    <th>Program</th>
                                    <th><?php echo $row['program'] ?></th>
                                </tr>
                                <tr>
                                    <th>Year Level</th>
                                    <th><?php echo $row['year_level'] ?></th>
                                </tr>

                                <tr>
                                    <th>Valid ID</th>
                                    <th><button type="button" data-toggle="modal" data-target="#Valid_ID"
                                            class="btn btn-primary">View Here</button></th>
                                    <!-- Modal -->
                                    <div class="modal fade" id="Valid_ID" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Valid ID
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <img src="<?php echo "upload_docu/".$row['fileName']."/".$row['valid_id'] ?>"
                                                        alt="sadsads">
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="width:100%" type="button" class="btn btn-primary"
                                                        data-dismiss="modal">DONE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                                <tr>
                                    <th>School ID</th>
                                    <th><button data-toggle="modal" data-target="#School_ID" type="button"
                                            class="btn btn-primary">View Here</button></th>


                                    <!-- Modal -->
                                    <div class="modal fade" id="School_ID" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">School ID
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <img src="<?php echo "upload_docu/".$row['fileName']."/".$row['School_ID'] ?>"
                                                        alt="sadsads">
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="width:100%" type="button" class="btn btn-primary"
                                                        data-dismiss="modal">DONE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                                <tr>
                                    <th>Barangay Residency</th>
                                    <th><button type="button" data-toggle="modal" data-target="#View_Barangay_Residency"
                                            class="btn btn-primary">View
                                            Here</button></th>
                                    <!-- Modal -->
                                    <div class="modal fade" id="View_Barangay_Residency" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Barangay
                                                        Residency
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <img src="<?php echo "upload_docu/".$row['fileName']."/".$row['Barangay_Residency'] ?>"
                                                        alt="sadsads">
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="width:100%" type="button" class="btn btn-primary"
                                                        data-dismiss="modal">DONE</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                                <?php if($row['scholar_type'] == 'New Applicant'): ?>
                                <tr>
                                    <th>Essay</th>
                                    <th><button class="btn btn-primary" type="button" id="View_essay">View
                                            Here</button></th>
                                </tr>

                                <?php endif; ?>

                                <tr>
                                    <th>Proof of Enrollment</th>
                                    <th><button type="button" id="Proof_of_Enrollment_view" class="btn btn-primary">View
                                            Here</button></th>
                                </tr>
                                <tr>
                                    <th>Report Card</th>
                                    <th><button type="button" id="View_Report_Card" class="btn btn-primary">View
                                            Here</button></th>
                                </tr>
                                <tr>
                                    <th>Proof of Income</th>
                                    <th><button type="button" id="View_roof_of_Income" class="btn btn-primary">View
                                            Here</button></th>
                                </tr>


                            </tbody>
                        </table>
                        <hr>


                        <!-- Modal -->
                        <form action="Function.php" method="POST" autocomplete="off" enctype="multipart/form-data">

                            <div class="modal fade" id="Approved_modal" tabindex="-1" role="dialog"
                                aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Alert</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body text-center">
                                            <h3 for="">Are you sure to approve this applicant?</h3>

                                            <img class="mb-5 border rounded-circle applicant_img" width="50px"
                                                src='<?php echo "upload_docu/".$row['fileName']."/".$row['picture'] ?>'>

                                            <p class="text-uppercase"><?php echo $row['full_name'] ?></p>
                                            <input type="hidden" value="<?php echo $row['full_name'] ?>"
                                                name="full_name">
                                            <input type="hidden" name="applicants_id" value="<?php echo $row['id'] ?>">
                                            <input type="hidden" name="applicants_email"
                                                value="<?php echo $row['email'] ?>">

                                        </div>
                                        <div class="modal-footer">
                                            <input type="hidden" name="approved_by"
                                                value="<?php echo $_SESSION['auth_user']['Email']; ?>">

                                            <button type="submit" name="Approve_Scholar_btn"
                                                class="btn btn-success btn-block">Approve
                                                Scholar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>


                        <button type="button" class="btn btn-success text-uppercase" data-toggle="modal"
                            data-target="#Approved_modal">
                            Approved
                        </button>

                        <button type="button" class="btn btn-info text-uppercase" data-toggle="modal"
                            data-target="#NotNow_modal">
                            Resubmit
                        </button>

                        <button type="button" class="btn btn-danger text-uppercase" data-toggle="modal"
                            data-target="#disapproved">
                            Disqualified
                        </button>
                        <!-- Modal resubmit -->
                        <form action="Function.php" method="POST" autocomplete="off" enctype="multipart/form-data">
                            <div class="modal fade" id="NotNow_modal" tabindex="-1" role="dialog"
                                aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Alert</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body text-left">
                                            <input type="hidden" name="applicants_email"
                                                value="<?php echo $row['email'] ?>">
                                            <input type="hidden" name="admin_name"
                                                value="<?php echo  $_SESSION['auth_user']['first_name']." ".$_SESSION['auth_user']['last_name']?>">
                                            <input type="hidden" name="applicants_id" value="<?php echo $row['id'] ?>">
                                            <input type="hidden" name="applicant_full_name"
                                                value="<?php echo $row['full_name']; ?>">

                                            <h4>Please indicate the Document that the applicants needs to resubmit.
                                            </h4>
                                            <br>


                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'school_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    School
                                                </h5>
                                            </div>


                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'program_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Program
                                                </h5>
                                            </div>






                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'valid_id_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Valid ID
                                                </h5>
                                            </div>




                                            <?php if($row['scholar_type'] == 'New Applicant'): ?>
                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'Essay_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Essay
                                                </h5>
                                            </div>
                                            <?php endif; ?>

                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'picture_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Picture
                                                </h5>
                                            </div>


                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'Proof_of_Enrollment_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Proof of Enrollment
                                                </h5>
                                            </div>


                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'School_ID_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    School ID
                                                </h5>
                                            </div>

                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'Report_Card_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Report Card
                                                </h5>
                                            </div>


                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'Barangay_Residency_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Barangay Residency
                                                </h5>
                                            </div>
                                            <div class="form-check">
                                                <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                    value="<?php echo 'Proof_of_Income_resubmit'?>">
                                                <h5 class="form-check-label">
                                                    Proof of Income
                                                </h5>
                                            </div>



                                            <hr>

                                            <div class="form-group">
                                                <h5 for="exampleFormControlTextarea1">Leave a message here...</h5>
                                                <div class="text-left">
                                                    <textarea placeholder="Please provide reasons for disapproval..."
                                                        name="resubmit_message" class="form-control" required
                                                        id="your_summernote_2"></textarea>
                                                </div>

                                            </div>
















                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" name="resubmit_btn"
                                                class="btn btn-info btn-block">Send</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                        <form action="Function.php" method="POST">
                            <!-- Modal Disapproved-->
                            <div class="modal fade" id="disapproved" tabindex="-1" role="dialog"
                                aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Alert</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>






                                        <input type="hidden" name="full_name" value="<?php echo $row['full_name']; ?>">
                                        <input type="hidden" name="applicants_id" value="<?php echo $row['id'] ?>">
                                        <input type="hidden" name="applicants_email"
                                            value="<?php echo $row['email'] ?>">



                                        <div class="modal-body">
                                            <h3 for="">Are you rejecting this Applicant?</h3>
                                            <div class="text-center">

                                                <img class="mb-5 border rounded-circle applicant_img" width="50px"
                                                    src='<?php echo "upload_docu/".$row['fileName']."/".$row['picture'] ?>'>

                                                <p class="text-uppercase"><?php echo $row['full_name'] ?></p>
                                            </div>

                                            <div class="">
                                                <h4>Reasons of Disapproval</h4>
                                                <div class="form-check">
                                                    <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                        value="<?php echo '-Not a Pasig resident for at least three (3) years '?>">
                                                    <h5 class="form-check-label">
                                                        Not a Pasig resident for at least three (3) years
                                                    </h5>
                                                </div>
                                                <div class="form-check">
                                                    <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                        value="<?php echo '-Income of parents/guardians exceeds PHP20,000 '?>">
                                                    <h5 class="form-check-label">
                                                        Income of parents/guardians exceeds PHP20,000
                                                    </h5>
                                                </div>
                                                <div class="form-check">
                                                    <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                        value="<?php echo '-Not currently enrolled'?>">
                                                    <h5 class="form-check-label">
                                                        Not currently enrolled
                                                    </h5>
                                                </div>
                                                <div class="form-check">
                                                    <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                        value="<?php echo '-Poor academic standing Failing to meet the minimum general average.'?>">
                                                    <h5 class="form-check-label">
                                                        Poor academic standing Failing to meet the minimum general
                                                        average.
                                                    </h5>
                                                </div>

                                                <div class="form-check">
                                                    <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                        value="<?php echo '-Having a grade of Failed, Incomplete, or Dropped. '?>">
                                                    <h5 class="form-check-label">
                                                        Having a grade of Failed, Incomplete, or Dropped.
                                                    </h5>
                                                </div>


                                                <div class="form-check">
                                                    <input name="checkbox[]" class="form-check-input" type="checkbox"
                                                        value="<?php echo '-Competition with other applicants'?>">
                                                    <h5 class="form-check-label">
                                                        Competition with other applicants
                                                    </h5>
                                                </div>




















                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox"
                                                        id="otherReasonCheckbox">
                                                    <h5 class="form-check-label">
                                                        Other reason
                                                    </h5>
                                                </div>
                                                <hr>
                                                <div style="display:none" id='other_reason' class="form-group">
                                                    <h5 for="exampleFormControlTextarea1">Other reasons for
                                                        disapproval.</h5>
                                                    <div class="text-left">
                                                        <textarea
                                                            placeholder="Please provide reasons for disapproval..."
                                                            name="resubmit_message" class="form-control"
                                                            id="your_summernote_disapproved"></textarea>
                                                    </div>
                                                </div>

                                            </div>



                                        </div>
                                        <div class="modal-footer">

                                            <button type="submit" name="Disapproved_btn"
                                                class="btn btn-danger btn-block">Disqualified
                                                Applicants</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>




                    </div>
                </div>
            </div>





            <?php
                }}
            ?>
        </div>
    </div>
</div>
</div>



<script>
// Get references to the checkbox and textarea elements
var otherReasonCheckbox = document.getElementById(
    'otherReasonCheckbox');
var textarea = document.getElementById('other_reason');

// Add an event listener to the checkbox for the 'change' event
otherReasonCheckbox.addEventListener('change', function() {
    // If the checkbox is checked, show the textarea; otherwise, hide it
    textarea.style.display = this.checked ? 'block' : 'none';
});
</script>
















<script>
let View_essay = document.getElementById('View_essay');
let done_view_esssay = document.getElementById('done_view_esssay');

View_essay.onclick = () => {
    let essay = document.getElementById('essay');
    essay.classList.remove("hide");
}
done_view_esssay.onclick = () => {
    let essay = document.getElementById('essay');
    essay.classList.add("hide");
}
</script>





<script>
let Proof_of_Enrollment_view = document.getElementById('Proof_of_Enrollment_view');
let View_Report_Card = document.getElementById('View_Report_Card');


let View_roof_of_Income = document.getElementById('View_roof_of_Income');







let done_view_Proof_of_Enrollment = document.getElementById('done_view_Proof_of_Enrollment');
let done_Report_Card = document.getElementById('done_Report_Card');


let done_Proof_of_Income = document.getElementById('done_Proof_of_Income');



Proof_of_Enrollment_view.onclick = () => {
    let Proof_of_Enrollment = document.getElementById('Proof_of_Enrollment');

    Proof_of_Enrollment.classList.remove("hide");
}

done_view_Proof_of_Enrollment.onclick = () => {
    let Proof_of_Enrollment = document.getElementById('Proof_of_Enrollment');
    Proof_of_Enrollment.classList.add("hide");
}

View_Report_Card.onclick = () => {
    let Report_Card = document.getElementById('Report_Card');
    Report_Card.classList.remove("hide");
}
done_Report_Card.onclick = () => {
    let Report_Card = document.getElementById('Report_Card');
    Report_Card.classList.add("hide");
}

View_roof_of_Income.onclick = () => {
    let Proof_of_Income = document.getElementById('Proof_of_Income');
    Proof_of_Income.classList.remove("hide");
}


done_Proof_of_Income.onclick = () => {
    let Proof_of_Income = document.getElementById('Proof_of_Income');
    Proof_of_Income.classList.add("hide");
}
</script>


<?php include('includes/footer.php') ?>
